name: achievement_box
description: A powerful application designed to help you develop good habits, break bad ones, and achieve your goals.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.3.5+9

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqlite3: ^2.1.0
  app_tutorial: ^1.0.6
  cherry_toast: ^1.8.0
  introduction_screen: ^3.1.12
  provider: ^6.1.1
  font_awesome_flutter: ^10.7.0
  badges: ^3.1.2
  intl: ^0.19.0
  sqlite3_flutter_libs: ^0.5.20
  path_provider: ^2.1.3
  restart_app: ^1.3.2
  adaptive_theme: ^3.6.0
  permission_handler: ^11.3.1
  device_info_plus: ^10.1.0
  file_picker: ^8.0.6
  flutter_animate: ^4.5.0
  http: ^1.2.2
  auto_height_grid_view: ^1.0.0
  animated_custom_dropdown: ^3.1.1
  auto_size_text: ^3.0.0
  localization_lite:
    git:
      url: https://github.com/hesham04Dev/localization_lite.git
  package_info_plus: ^8.1.1
  mailto: ^2.0.0
  url_launcher: ^6.3.1
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/localization/

  fonts:
    - family: Dubai
      fonts:
        - asset: assets/fonts/DubaiW23-Regular.ttf
        - asset: assets/fonts/DubaiW23-Bold.ttf
          weight: 800